# arquivo de configuração do vale
#
# para mais informações:
# https://vale.sh/docs/vale-ini

StylesPath = doc/.vale
MinAlertLevel = suggestion

IgnoredScopes = code, text.frontmatter.redirect_to

[*.md]
BasedOnStyles = diwata_base, diwata_docs

# ignorar marcação de svg
TokenIgnores = \{\{< icon .*?>\}\}